<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="adminHome.aspx.cs" Inherits="AdminHome" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br/>
    <div class="container">
    <div class="jumbotron col-sm-12" style="border :10px solid maroon;text-align:center">
        <asp:Button ID="Button2"  runat="server" Style="margin-left:950px;" Text="Logout" BorderColor="#CC0000" Width="100px" Font-Bold="True" OnClick="Button2_Click" />
        <br/>
        <asp:Panel ID="Panel1" runat="server" BackColor="#FFFF66" BorderColor="#9966FF" BorderStyle="Solid" Height="210px" Width="450px" style="text-align:left">
            <asp:HyperLink ID="registerUserLink" runat="server" Font-Bold="True" Font-Names="Arial Black" NavigateUrl="~/view_allRegitration.aspx">* Click here To See All Register Users</asp:HyperLink>
            <br />
            <br />
            <asp:HyperLink ID="complaintsLink" runat="server" Font-Bold="True" Font-Names="Arial Black" NavigateUrl="~/view_allComplaints.aspx">* Click Here To see All User Compaints</asp:HyperLink>
            <br />
            <br />
            <asp:HyperLink ID="clubhousebookingLink" runat="server" Font-Bold="True" Font-Names="Arial Black" NavigateUrl="~/view_allClubHouseBooking.aspx">* Click Here To See All Club House Booking</asp:HyperLink>
            <br />
            <br />        
            <asp:HyperLink ID="HyperLink1" runat="server" Font-Bold="True" Font-Names="Arial Black" NavigateUrl="~/view_allfeedback.aspx">* Click Here To See All Feedbacks</asp:HyperLink>
        </asp:Panel>
     <br />
    <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Names="Arial Black" Text="Add Notification To User Side : "></asp:Label>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="notification" ErrorMessage="*Please Add Notification  Meassage" ForeColor="#FF6600"></asp:RequiredFieldValidator>
    <br />
    <asp:TextBox ID="notification" runat="server" Height="64px" Width="483px"></asp:TextBox>

    <br />
    <br />
    <asp:Button ID="Button1" runat="server" Text="Add Notificaiton" Cssclass="btn-info" OnClick="Button1_Click" />
        <br />
    <br />
        <asp:Label ID="Label2" runat="server" Text="List of Notification : "></asp:Label>
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="nid" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="nid" HeaderText="Nid" InsertVisible="False" ReadOnly="True" SortExpression="nid" />
                <asp:BoundField DataField="heading" HeaderText="Heading" SortExpression="heading" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Notification] WHERE [nid] = @nid" InsertCommand="INSERT INTO [Notification] ([heading]) VALUES (@heading)" SelectCommand="SELECT * FROM [Notification]" UpdateCommand="UPDATE [Notification] SET [heading] = @heading WHERE [nid] = @nid">
            <DeleteParameters>
                <asp:Parameter Name="nid" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="heading" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="heading" Type="String" />
                <asp:Parameter Name="nid" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        
        <br />
    <br/>
    </div>
    </div>
</asp:Content>

