<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="view_allClubHouseBooking.aspx.cs" Inherits="view_allClubHouseBooking" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br/>
    <div class="container">
        <div class="jumbotron">
            <asp:Button ID="back" CssClass="btn-primary btn-lg" style="margin-left:950px" runat="server" Text="Back" BorderColor="#CC0000" BorderStyle="Solid" Font-Bold="True" PostBackUrl="~/adminHome.aspx" /> 
            <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Names="Arial Black" Text="List of All Club House Bookings :" Font-Size="Larger"></asp:Label>
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" InsertVisible="False" ReadOnly="True" />
                    <asp:BoundField DataField="blockno" HeaderText="Block No" SortExpression="blockno" />
                    <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                    <asp:BoundField DataField="mobile" HeaderText="Mobile" SortExpression="mobile" />
                    <asp:BoundField DataField="start_date" HeaderText="Start Date" SortExpression="start_date" />
                    <asp:BoundField DataField="end_date" HeaderText="End Date" SortExpression="end_date" />
                    <asp:BoundField DataField="time" HeaderText="Time" SortExpression="time" />
                    <asp:BoundField DataField="note" HeaderText="Note" SortExpression="note" />
                    <asp:BoundField DataField="rate" HeaderText="Rate" SortExpression="rate" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [clubhouse] WHERE [Id] = @Id" InsertCommand="INSERT INTO [clubhouse] ([blockno], [name], [mobile], [start_date], [end_date], [time], [note], [rate]) VALUES (@blockno, @name, @mobile, @start_date, @end_date, @time, @note, @rate)" SelectCommand="SELECT * FROM [clubhouse]" UpdateCommand="UPDATE [clubhouse] SET [blockno] = @blockno, [name] = @name, [mobile] = @mobile, [start_date] = @start_date, [end_date] = @end_date, [time] = @time, [note] = @note, [rate] = @rate WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="blockno" Type="Int32" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="mobile" Type="String" />
                    <asp:Parameter DbType="Date" Name="start_date" />
                    <asp:Parameter DbType="Date" Name="end_date" />
                    <asp:Parameter Name="time" Type="String" />
                    <asp:Parameter Name="note" Type="String" />
                    <asp:Parameter Name="rate" Type="Decimal" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="blockno" Type="Int32" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="mobile" Type="String" />
                    <asp:Parameter DbType="Date" Name="start_date" />
                    <asp:Parameter DbType="Date" Name="end_date" />
                    <asp:Parameter Name="time" Type="String" />
                    <asp:Parameter Name="note" Type="String" />
                    <asp:Parameter Name="rate" Type="Decimal" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
             
        </div>
    </div>
    <br/>
</asp:Content>

